/* Axiom content. Tools are the axioms and earned lemmas you drag onto a goal;
   theorems are the puzzles. Every par in this file is produced by the kernel's own
   solver in tools/par.js, never typed by hand. */
const Content = (function () {
  'use strict';

  /* ---------------- tools ---------------- */
  const TOOLS = [
    /* equality, the plumbing of every region */
    { id: 'eq-refl', name: 'Anything equals itself', text: 'x = x, for any x at all.',
      f: 'all X. eq(X,X)' },
    { id: 'eq-sym', name: 'Equality runs both ways', text: 'If x = y then y = x.',
      f: 'all X Y. eq(X,Y) -> eq(Y,X)' },
    { id: 'eq-trans', name: 'Equals of the same thing', text: 'If x = y and y = z then x = z. You choose the middle term.',
      f: 'all X Y Z. eq(X,Y) -> eq(Y,Z) -> eq(X,Z)' },
    { id: 'cancel', name: 'Take the same amount off both', text: 'If x + z = y + z then x = y.',
      f: 'all X Y Z. eq(add(X,Z),add(Y,Z)) -> eq(X,Y)' },
    { id: 'add-comm', name: 'Addition does not care about order', text: 'x + y = y + x.',
      f: 'all X Y. eq(add(X,Y),add(Y,X))' },

    /* geometry */
    { id: 'seg-flip', name: 'A segment read backwards', text: 'The segment AB is the segment BA.',
      f: 'all X Y. eq(seg(X,Y),seg(Y,X))' },
    { id: 'ang-flip', name: 'An angle read backwards', text: 'The angle ABC is the angle CBA.',
      f: 'all X Y Z. eq(ang(X,Y,Z),ang(Z,Y,X))' },
    { id: 'sss', name: 'Side, side, side', text: 'Three matching sides make the triangles congruent.',
      f: 'all A B C D E F. eq(seg(A,B),seg(D,E)) -> eq(seg(B,C),seg(E,F)) -> eq(seg(A,C),seg(D,F)) -> cong(tri(A,B,C),tri(D,E,F))' },
    { id: 'sas', name: 'Side, angle, side', text: 'Two matching sides and the angle between them make the triangles congruent.',
      f: 'all A B C D E F. eq(seg(A,B),seg(D,E)) -> eq(ang(B,A,C),ang(E,D,F)) -> eq(seg(A,C),seg(D,F)) -> cong(tri(A,B,C),tri(D,E,F))' },
    { id: 'asa', name: 'Angle, side, angle', text: 'Two matching angles and the side between them make the triangles congruent.',
      f: 'all A B C D E F. eq(ang(C,A,B),ang(F,D,E)) -> eq(seg(A,B),seg(D,E)) -> eq(ang(A,B,C),ang(D,E,F)) -> cong(tri(A,B,C),tri(D,E,F))' },
    { id: 'aas', name: 'Angle, angle, side', text: 'Two matching angles and a side outside them make the triangles congruent.',
      f: 'all A B C D E F. eq(ang(A,B,C),ang(D,E,F)) -> eq(ang(A,C,B),ang(D,F,E)) -> eq(seg(B,C),seg(E,F)) -> cong(tri(A,B,C),tri(D,E,F))' },
    { id: 'cpctc-a1', name: 'Matching angle at the first corner', text: 'Congruent triangles have equal angles at their first named corner.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(ang(B,A,C),ang(E,D,F))' },
    { id: 'cpctc-a2', name: 'Matching angle at the second corner', text: 'Congruent triangles have equal angles at their second named corner.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(ang(A,B,C),ang(D,E,F))' },
    { id: 'cpctc-a3', name: 'Matching angle at the third corner', text: 'Congruent triangles have equal angles at their third named corner.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(ang(A,C,B),ang(D,F,E))' },
    { id: 'cpctc-s1', name: 'Matching first side', text: 'Congruent triangles have equal first sides.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(seg(A,B),seg(D,E))' },
    { id: 'cpctc-s2', name: 'Matching second side', text: 'Congruent triangles have equal second sides.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(seg(B,C),seg(E,F))' },
    { id: 'cpctc-s3', name: 'Matching third side', text: 'Congruent triangles have equal third sides.',
      f: 'all A B C D E F. cong(tri(A,B,C),tri(D,E,F)) -> eq(seg(A,C),seg(D,F))' },
    { id: 'supp-sum', name: 'Supplementary angles fill a straight line', text: 'If two angles are supplementary, together they make a straight angle.',
      f: 'all X Y. supp(X,Y) -> eq(add(X,Y),straight)' },
    { id: 'supp-flip', name: 'Supplementary either way round', text: 'If x is supplementary to y then y is supplementary to x.',
      f: 'all X Y. supp(X,Y) -> supp(Y,X)' },
    { id: 'par-alt', name: 'Parallel lines, alternate angles', text: 'A line crossing two parallels makes equal alternate angles.',
      f: 'all A B C D. par(line(A,B),line(C,D)) -> eq(ang(A,B,C),ang(D,C,B))' },

    /* number */
    { id: 'zero-even', name: 'Zero is even', text: 'Nought is an even number.', f: 'even(0)' },
    { id: 'even-odd', name: 'Every number is even or odd', text: 'There is no third option.', f: 'all N. even(N) | odd(N)', fwd: true },
    { id: 'not-both', name: 'No number is both', text: 'Even and odd cannot hold of the same number.',
      f: 'all N. even(N) -> odd(N) -> false' },
    { id: 'even-succ', name: 'One more than an even number', text: 'Add one to an even number and you get an odd one.',
      f: 'all N. even(N) -> odd(s(N))' },
    { id: 'odd-succ', name: 'One more than an odd number', text: 'Add one to an odd number and you get an even one.',
      f: 'all N. odd(N) -> even(s(N))' },
    { id: 'even-sum', name: 'Even plus even', text: 'The sum of two even numbers is even.',
      f: 'all M N. even(M) -> even(N) -> even(add(M,N))' },
    { id: 'odd-sum', name: 'Odd plus odd', text: 'The sum of two odd numbers is even.',
      f: 'all M N. odd(M) -> odd(N) -> even(add(M,N))' },
    { id: 'mix-sum', name: 'Even plus odd', text: 'An even number plus an odd number is odd.',
      f: 'all M N. even(M) -> odd(N) -> odd(add(M,N))' },
    { id: 'even-sq', name: 'The square of an even number', text: 'If n is even then n squared is even.',
      f: 'all N. even(N) -> even(mul(N,N))' },
    { id: 'odd-sq', name: 'The square of an odd number', text: 'If n is odd then n squared is odd.',
      f: 'all N. odd(N) -> odd(mul(N,N))' },
    { id: 'even-mul', name: 'An even factor', text: 'An even number times anything is even.',
      f: 'all M N. even(M) -> even(mul(M,N))' },
    { id: 'div-refl', name: 'Everything divides itself', text: 'a divides a.', f: 'all A. div(A,A)' },
    { id: 'div-trans', name: 'Divisors of divisors', text: 'If a divides b and b divides c then a divides c.',
      f: 'all A B C. div(A,B) -> div(B,C) -> div(A,C)' },
    { id: 'div-sum', name: 'A common divisor of a sum', text: 'If a divides b and a divides c then a divides b + c.',
      f: 'all A B C. div(A,B) -> div(A,C) -> div(A,add(B,C))' },
    { id: 'div-mul', name: 'A divisor survives multiplication', text: 'If a divides b then a divides b times anything.',
      f: 'all A B C. div(A,B) -> div(A,mul(B,C))' },
    { id: 'even-div2', name: 'Even means divisible by two', text: 'If n is even then 2 divides n.',
      f: 'all N. even(N) -> div(2,N)' },
    { id: 'div2-even', name: 'Divisible by two means even', text: 'If 2 divides n then n is even.',
      f: 'all N. div(2,N) -> even(N)' },
    { id: 'prime-factor', name: 'Every number above one has a prime factor', text: 'Applied here to n factorial plus one.',
      f: 'all N. ex P. prime(P) & div(P,fact1(N))', fwd: true },
    { id: 'fact-big', name: 'A prime dividing n! + 1 is large', text: 'No prime up to n divides n! + 1, so such a prime must exceed n.',
      f: 'all N P. prime(P) -> div(P,fact1(N)) -> lt(N,P)' }
  ];

  /* ---------------- regions ---------------- */
  const REGIONS = [
    { id: 'riverlands', name: 'The Riverlands of Geometry', era: 'Alexandria, about 300 BC',
      blurb: 'Euclid drew the first map of reasoning here. Everything downstream is built on these banks.',
      gate: 0 },
    { id: 'steppes', name: 'The Numbered Steppes', era: 'Whole numbers, from Euclid to Gauss',
      blurb: 'Parity, divisibility and the primes. Open country where a single case split settles everything.',
      gate: 8 },
    { id: 'fens', name: 'The Logic Fens', era: 'Aristotle to Frege',
      blurb: 'No triangles, no numbers. Only the shapes of argument themselves, which is why they hold everywhere.',
      gate: 18 }
  ];

  /* ---------------- theorems ---------------- */
  const THEOREMS = [
    /* ============ Riverlands ============ */
    { id: 'r01', region: 'riverlands', name: 'The first step',
      prose: 'A segment is equal to itself.',
      statement: 'eq(seg(A,B),seg(A,B))',
      tools: ['eq-refl'],
      lemma: 'A segment is equal to itself.',
      hints: ['You are not being asked to do anything clever. Look at what the tool already says.',
              'A tool with no conditions attached closes a goal on its own.',
              'Drag "Anything equals itself" onto the amber goal.'] },

    { id: 'r02', region: 'riverlands', name: 'Both directions',
      prose: 'Given that a equals b and that b equals c, you can still conclude that b equals a. The second fact is a distraction.',
      statement: 'eq(a,b) -> eq(b,c) -> eq(b,a)',
      tools: ['eq-sym', 'eq-refl'],
      lemma: 'Equality can be read in either direction.',
      hints: ['The goal is an arrow. An arrow is a promise: give me the left, and I owe you the right.',
              'Take both promises. Not every hypothesis has to be used.',
              'Suppose twice, then use "Equality runs both ways".'] },

    { id: 'r03', region: 'riverlands', name: 'Two things at once',
      prose: 'From one equality you get both its reverse and a self-equality.',
      statement: 'eq(a,b) -> eq(b,a) & eq(a,a)',
      tools: ['eq-sym', 'eq-refl'],
      lemma: 'A conjunction is proved one half at a time.',
      hints: ['An "and" in the goal is two separate jobs, not one harder one.',
              'Split the goal, then finish each half with its own tool.',
              'Suppose, split, then one tool on each branch.'] },

    { id: 'r04', region: 'riverlands', name: 'The middle term',
      prose: 'Equality carries along a chain: from a to b to c to d.',
      statement: 'eq(a,b) -> eq(b,c) -> eq(c,d) -> eq(a,d)',
      tools: ['eq-trans', 'eq-sym'],
      lemma: 'Equality chains through a middle term.',
      hints: ['The tool that fits needs something the goal does not mention.',
              'Transitivity has three slots and your goal only fills two. You choose the third.',
              'Use "Equals of the same thing" and name y as the middle term.'] },

    { id: 'r05', region: 'riverlands', name: 'Turning a segment around',
      prose: 'If AB equals CD then BA equals DC.',
      statement: 'eq(seg(A,B),seg(C,D)) -> eq(seg(B,A),seg(D,C))',
      tools: ['seg-flip', 'eq-trans', 'eq-sym'],
      lemma: 'Reversing both segments preserves equality.',
      hints: ['BA is not literally AB, but a tool says they are equal.',
              'Walk from BA to AB to CD to DC. Each step is one equality.',
              'Chain twice with "Equals of the same thing", using AB and then CD as middles.'] },

    { id: 'r06', region: 'riverlands', name: 'Supplements of the same angle',
      prose: 'Two angles that are each supplementary to the same third angle are equal. This is the reason opposite angles at a crossing are equal.',
      statement: 'supp(a,c) -> supp(b,c) -> eq(a,b)',
      tools: ['supp-sum', 'cancel', 'eq-trans', 'eq-sym'],
      lemma: 'Angles supplementary to the same angle are equal.',
      hints: ['Both angles complete the same straight line. Write that down as two sums.',
              'If a + c and b + c are both the straight angle, they are equal to each other.',
              'Cancel the common c, then chain the two sums through the straight angle.'] },

    { id: 'r07', region: 'riverlands', name: 'The bridge of asses', keystone: true,
      prose: 'If two sides of a triangle are equal, the angles opposite them are equal.',
      statement: 'eq(seg(A,B),seg(A,C)) -> eq(ang(A,B,C),ang(A,C,B))',
      tools: ['sas', 'cpctc-a2', 'eq-sym', 'ang-flip'],
      lemma: 'Base angles of an isosceles triangle are equal.',
      hints: ['You have one triangle and you need two. Nothing stops you comparing it with itself.',
              'Match triangle ABC against triangle ACB. Which sides and which angle line up?',
              'Aim at the matching angle at the second corner, then earn the congruence with side, angle, side.'],
      vignette: {
        title: 'Pons Asinorum',
        era: 'Euclid, Elements I.5, about 300 BC',
        body: ['This is the fifth proposition of the Elements, and for something like eighteen centuries it was the place where students stopped. Medieval scholars called it pons asinorum, the bridge of asses: the bridge only the sure footed cross. The name was not kind, but it was accurate about where the difficulty sits. Nothing before it asks you to invent anything.',
               'The trick you just used is not the one Euclid printed. His proof extends the two equal sides and compares two larger triangles, which is fiddly to draw and worse to remember. The proof here is the one attributed to Pappus of Alexandria, six hundred years later: compare the triangle with itself, read the other way round. It looks like cheating and it is completely sound, which is a combination mathematics never entirely stops enjoying.',
               'Lewis Carroll, who taught geometry at Oxford under his own name, thought Euclid I.5 was the finest test of whether a student could reason at all. You have now crossed it.'] } },

    { id: 'r08', region: 'riverlands', name: 'The converse bridge',
      prose: 'If two angles of a triangle are equal, the sides opposite them are equal.',
      statement: 'eq(ang(A,B,C),ang(A,C,B)) -> eq(seg(A,B),seg(A,C))',
      tools: ['aas', 'cpctc-s1', 'eq-sym', 'seg-flip'],
      lemma: 'A triangle with two equal angles has two equal sides.',
      hints: ['The same self comparison works, but you now start from angles.',
              'Angle, angle, side is the congruence rule that takes two angles as input.',
              'Aim at the matching first side, then earn the congruence with angle, angle, side.'] },

    { id: 'r09', region: 'riverlands', name: 'Three sides settle everything',
      prose: 'Triangles with three matching sides have matching angles too.',
      statement: 'eq(seg(A,B),seg(D,E)) -> eq(seg(B,C),seg(E,F)) -> eq(seg(A,C),seg(D,F)) -> eq(ang(A,B,C),ang(D,E,F))',
      tools: ['sss', 'cpctc-a2'],
      lemma: 'Three matching sides force the angles to match.',
      hints: ['There are three arrows in the goal. Take all three promises first.',
              'Congruence is the bridge between sides and angles. Prove it, then read an angle off it.',
              'Aim at the matching angle at the second corner, then use side, side, side.'] },

    { id: 'r10', region: 'riverlands', name: 'Congruence looks both ways',
      prose: 'If the first triangle is congruent to the second, the second is congruent to the first.',
      statement: 'cong(tri(A,B,C),tri(D,E,F)) -> cong(tri(D,E,F),tri(A,B,C))',
      tools: ['sss', 'cpctc-s1', 'cpctc-s2', 'cpctc-s3', 'eq-sym'],
      lemma: 'Triangle congruence can be read in either direction.',
      hints: ['You cannot flip congruence directly. You can rebuild it from its sides.',
              'Read all three sides off the congruence you have, reverse each, and reassemble.',
              'Side, side, side, then equality both ways on each of the three premises.'] },

    { id: 'r11', region: 'riverlands', name: 'Alternate angles',
      prose: 'A line crossing two parallel lines makes equal alternate angles, and the equality reads both ways.',
      statement: 'par(line(A,B),line(C,D)) -> eq(ang(D,C,B),ang(A,B,C))',
      tools: ['par-alt', 'eq-sym'],
      lemma: 'Alternate angles across parallels are equal, in either order.',
      hints: ['The tool gives you the equality one way round.',
              'Take the promise first, then fix the order.',
              'Suppose, reverse the equality, then use the parallel lines tool.'] },

    { id: 'r12', region: 'riverlands', name: 'Equal to a common angle',
      prose: 'Two angles each equal to a third are equal to each other, even read in opposite orders.',
      statement: 'eq(ang(A,B,C),x) -> eq(ang(D,E,F),x) -> eq(ang(C,B,A),ang(F,E,D))',
      tools: ['eq-trans', 'eq-sym', 'ang-flip'],
      lemma: 'Angles equal to a common angle are equal, in any reading.',
      hints: ['Reversed angle names are equal to the forward ones. That is a tool, not an assumption.',
              'You have a hub: both angles are equal to x. Route through it.',
              'Chain through x, and use the reversed angle tool at each end.'] },

    { id: 'r13', region: 'riverlands', name: 'An isosceles triangle from a congruence',
      prose: 'If a triangle is congruent to itself reversed, its base angles are equal, read either way round.',
      statement: 'cong(tri(A,B,C),tri(A,C,B)) -> eq(ang(A,C,B),ang(A,B,C))',
      tools: ['cpctc-a2', 'eq-sym'],
      lemma: 'A self reversed congruence gives equal base angles.',
      hints: ['This is one tool away once the promise is taken.',
              'Which corner of the congruence carries the angle you want?',
              'Suppose, then read off the matching angle at the second corner.'] },

    { id: 'r14', region: 'riverlands', name: 'The straight line, twice over',
      prose: 'If two angles are supplementary in either order, each sum makes the straight angle.',
      statement: 'supp(a,b) -> eq(add(b,a),straight)',
      tools: ['supp-sum', 'supp-flip', 'eq-trans', 'add-comm'],
      lemma: 'A supplementary pair sums to a straight angle in either order.',
      hints: ['You know a + b. You want b + a.',
              'Either turn the angles round first, or turn the sum round first.',
              'Supplementary either way round, then the sum tool.'] },

    /* ============ Numbered Steppes ============ */
    { id: 's01', region: 'steppes', name: 'Odd and odd',
      prose: 'The sum of two odd numbers is even, whichever order you add them in.',
      statement: 'odd(m) -> odd(n) -> even(add(n,m))',
      tools: ['odd-sum', 'even-sum'],
      lemma: 'Odd plus odd is even.',
      hints: ['Take both promises before you look for a tool.',
              'One tool says exactly this.',
              'Suppose twice, then use "Odd plus odd".'] },

    { id: 's02', region: 'steppes', name: 'Two odd squares',
      prose: 'The squares of two odd numbers add up to an even number.',
      statement: 'odd(m) -> odd(n) -> even(add(mul(m,m),mul(n,n)))',
      tools: ['odd-sq', 'odd-sum', 'even-sum'],
      lemma: 'The sum of two odd squares is even.',
      hints: ['Work backwards from the sum, not forwards from the two numbers.',
              'Which tool produces an even sum, and what does it demand of the two parts?',
              'Aim at "Odd plus odd", then square each number in turn.'] },

    { id: 's03', region: 'steppes', name: 'A divisor of a divisor',
      prose: 'Divisibility chains as far along as you like.',
      statement: 'div(a,b) -> div(b,c) -> div(c,d) -> div(a,d)',
      tools: ['div-trans', 'div-refl'],
      lemma: 'Divisibility chains.',
      hints: ['Three promises first.', 'The tool named for chains is the one you want, more than once.',
              'Use "Divisors of divisors" on the whole span, then again on the part you still owe.'] },

    { id: 's04', region: 'steppes', name: 'A divisor of a sum',
      prose: 'If a divides b then a divides b plus b, times anything at all.',
      statement: 'div(a,b) -> div(a,mul(add(b,b),c))',
      tools: ['div-sum', 'div-mul'],
      lemma: 'A common divisor divides the sum.',
      hints: ['Peel the goal from the outside in: first the multiplication, then the sum.',
              'One tool strips the times, another strips the plus.',
              'Suppose, use the multiplication tool, then the sum tool.'] },

    { id: 's05', region: 'steppes', name: 'Even, and therefore even squared',
      prose: 'If 2 divides n then n squared is even.',
      statement: 'div(2,n) -> even(mul(n,n))',
      tools: ['div2-even', 'even-sq', 'even-div2'],
      lemma: 'A number divisible by two has an even square.',
      hints: ['Divisibility by two and evenness are two names for the same thing here.',
              'Get from divisibility to evenness first, then square.',
              'Aim at "The square of an even number", and earn its premise with "Divisible by two means even".'] },

    { id: 's06', region: 'steppes', name: 'Nothing is both',
      prose: 'A number cannot be both even and odd, so if it is odd it is not even.',
      statement: 'odd(n) -> ~even(n)',
      tools: ['not-both', 'even-odd'],
      lemma: 'Odd numbers are not even.',
      hints: ['A "not" in the goal is still an arrow: suppose the thing, and derive a contradiction.',
              'Once you have both evenness and oddness of the same number, one tool ends it.',
              'Suppose twice, then use "No number is both".'] },

    { id: 's07', region: 'steppes', name: 'The parity of a square', keystone: true,
      prose: 'If n squared is even then n itself is even. This is the step that makes the square root of two irrational.',
      statement: 'even(mul(n,n)) -> even(n)',
      tools: ['even-odd', 'not-both', 'odd-sq', 'even-sq'],
      lemma: 'A number with an even square is even.',
      hints: ['You cannot get at n directly. But you know something about every number.',
              'Every number is even or odd. Bring that fact in about n and split the argument.',
              'In the odd case, square it and collide with what you were given.'],
      vignette: {
        title: 'The diagonal that broke a school',
        era: 'Croton, about 450 BC',
        body: ['The Pythagoreans believed that every length was a ratio of whole numbers. The diagonal of a unit square is not, and the proof that it is not turns entirely on the theorem you just finished.',
               'Suppose the diagonal were a fraction in lowest terms, p over q. Then p squared is twice q squared, so p squared is even. By what you have proved, p is even. Write p as twice something, substitute, and q squared turns out to be even as well, so q is even too. But the fraction was in lowest terms, and both halves cannot be even. There is no such fraction.',
               'The legend says the Pythagorean who leaked this was drowned at sea. The legend is almost certainly false and has survived for two and a half thousand years anyway, which tells you how badly the result landed. It is the first time in recorded mathematics that a proof forced people to accept something they did not want to be true.'] } },

    { id: 's08', region: 'steppes', name: 'Either way, even',
      prose: 'Whatever n is, n or n plus one is even.',
      statement: 'even(n) | even(s(n))',
      tools: ['even-odd', 'odd-succ', 'even-succ'],
      lemma: 'Of any number and its successor, one is even.',
      hints: ['You do not know which side of the "or" is true, so find out.',
              'Bring in the fact that n is even or odd, then take the two cases separately.',
              'In each case one side of the goal is within a single tool.'] },

    { id: 's09', region: 'steppes', name: 'One more, one less',
      prose: 'If n is even then n plus one is odd and not even.',
      statement: 'even(n) -> odd(s(n)) & ~even(s(n))',
      tools: ['even-succ', 'not-both'],
      lemma: 'The successor of an even number is odd and not even.',
      hints: ['Two jobs joined by an "and".', 'The second half is a "not": suppose it and look for the collision.',
              'Suppose, split, and use the successor tool on both branches.'] },

    { id: 's10', region: 'steppes', name: 'Every number is even or odd',
      prose: 'Proved for all numbers at once, by induction: true of nought, and passed on from each number to the next.',
      statement: 'all n. even(n) | odd(n)',
      induction: true,
      tools: ['zero-even', 'even-succ', 'odd-succ'],
      lemma: 'Every whole number is even or odd.',
      hints: ['A claim about every number is a claim about nought, plus a claim about passing it on.',
              'The base case is one tool. The step assumes it for n and needs it for n plus one.',
              'Induct, then in the step suppose the assumption and split into its two cases.'] },

    { id: 's11', region: 'steppes', name: 'There is an even number',
      prose: 'Something is even. Producing one is the whole proof.',
      statement: 'ex X. even(X)',
      tools: ['zero-even'],
      lemma: 'An existence claim is settled by naming a witness.',
      hints: ['You are not asked which number. You are asked for one.',
              'Name a number you already have a tool about.',
              'Name nought, then use "Zero is even".'] },

    { id: 's12', region: 'steppes', name: 'An even number with an even square',
      prose: 'There is a number that is even and whose square is even too.',
      statement: 'ex X. even(X) & even(mul(X,X))',
      tools: ['zero-even', 'even-sq'],
      lemma: 'A witness can be made to satisfy two conditions at once.',
      hints: ['Name your number first, then deal with the two demands.',
              'The same witness has to serve both halves of the "and".',
              'Name nought, split, then one tool each.'] },

    { id: 's13', region: 'steppes', name: 'A prime beyond any number', keystone: true,
      prose: 'For every number there is a prime larger than it. Euclid proved this in five moves and nobody has improved on the idea in twenty three centuries.',
      statement: 'all N. ex P. prime(P) & lt(N,P)',
      tools: ['prime-factor', 'fact-big'],
      lemma: 'There is no largest prime.',
      hints: ['Fix a number and think about what you could build from it that no small prime divides.',
              'Multiply everything up to n together and add one. What can divide that?',
              'Bring in the prime factor of n! + 1, name it, and offer it as your witness.'],
      vignette: {
        title: 'Euclid IX.20',
        era: 'Alexandria, about 300 BC',
        body: ['Euclid does not say "there are infinitely many primes". Greek mathematics did not talk about completed infinities. He says: prime numbers are more than any assigned multitude of prime numbers. Give me a list, and I will give you one that is not on it.',
               'The construction is the one you just used. Multiply the numbers on the list together, add one, and ask what divides the result. Whatever prime divides it cannot be any prime on your list, because dividing the product exactly and dividing the product plus one exactly would mean dividing one. So there is a prime you missed. Every time. Forever.',
               'It is often called the most beautiful proof in mathematics, and the reason is that it is constructive and short and answers a question about infinity without ever mentioning infinity. G. H. Hardy wrote that it is as fresh and significant as when it was discovered, and that two thousand years have not written a wrinkle on it.'] } },

    { id: 's14', region: 'steppes', name: 'Not every number is odd',
      prose: 'It is false that every number is odd.',
      statement: '~(all X. odd(X))',
      tools: ['zero-even', 'not-both'],
      lemma: 'A universal claim falls to a single counterexample.',
      hints: ['To refute a claim about every number, you only need one number.',
              'Suppose the claim, then aim it at a number you know something about.',
              'Suppose, use the assumption at nought, and collide it with "Zero is even".'] },

    { id: 's15', region: 'steppes', name: 'Even sums, doubled',
      prose: 'If m and n are both even then so is m + n, and so is that sum added to itself.',
      statement: 'even(m) -> even(n) -> even(add(add(m,n),add(m,n)))',
      tools: ['even-sum'],
      lemma: 'Evenness survives repeated addition.',
      hints: ['One tool, used more than once.', 'Prove the inner sum is even first, then feed it to itself.',
              'Suppose twice, then apply the sum tool to the outer sum before the inner one.'] },

    { id: 's16', region: 'steppes', name: 'Odd, squared, and not even',
      prose: 'If n is odd then n squared is not even.',
      statement: 'odd(n) -> ~even(mul(n,n))',
      tools: ['odd-sq', 'not-both'],
      lemma: 'Odd squares are not even.',
      hints: ['The "not" is an arrow. Suppose the thing it denies.',
              'You then hold evenness and can derive oddness of the same number.',
              'Suppose twice, use "No number is both" on n squared, then square the odd number.'] },

    /* ============ Logic Fens ============ */
    { id: 'f01', region: 'fens', name: 'Order does not matter',
      prose: 'If P and Q, then Q and P.',
      statement: 'P & Q -> Q & P',
      tools: [],
      lemma: 'Conjunction can be reordered.',
      hints: ['Take the promise. Notice what lands among your hypotheses.',
              'An "and" you assume is split for you. An "and" you must prove is not.',
              'Suppose, then split.'] },

    { id: 'f02', region: 'fens', name: 'A fact needs no reason',
      prose: 'If P holds, then P holds no matter what else you are told.',
      statement: 'P -> Q -> P',
      tools: [],
      lemma: 'A truth survives extra assumptions.',
      hints: ['Both arrows are promises you can simply accept.',
              'After taking both, the goal is already a hypothesis.',
              'Suppose twice.'] },

    { id: 'f03', region: 'fens', name: 'Detachment',
      prose: 'If P holds and P implies Q, then Q holds. The oldest rule in logic.',
      statement: 'P & (P -> Q) -> Q',
      tools: [],
      lemma: 'Modus ponens.',
      hints: ['The assumed "and" gives you two hypotheses, one of which is itself an arrow.',
              'Hypotheses are tools too. Aim one at the goal.',
              'Suppose, then use the arrow among your hypotheses.'] },

    { id: 'f04', region: 'fens', name: 'Arrows compose',
      prose: 'If P implies Q and Q implies R, then P implies R.',
      statement: '(P -> Q) -> (Q -> R) -> (P -> R)',
      tools: [],
      lemma: 'Implication is transitive.',
      hints: ['Three arrows in the goal, so three promises to take.',
              'Work backwards from R, not forwards from P.',
              'Suppose three times, then use the second arrow, then the first.'] },

    { id: 'f05', region: 'fens', name: 'Either way round',
      prose: 'If P or Q, then Q or P.',
      statement: 'P | Q -> Q | P',
      tools: [],
      lemma: 'Disjunction can be reordered.',
      hints: ['You are handed an "or" you did not choose. Handle both possibilities.',
              'Splitting into cases is a move. In each case you know which side of the goal to aim at.',
              'Suppose, take cases, then pick the matching side in each.'] },

    { id: 'f06', region: 'fens', name: 'Double negation',
      prose: 'If it is not the case that P is false, then P.',
      statement: '~~P -> P',
      tools: [],
      lemma: 'Two negations cancel.',
      hints: ['There is no way to build P out of nothing. So do not build it.',
              'Assume the goal is false and hunt for the impossible.',
              'Suppose, contradict, then use the double negative on the negative you just assumed.'] },

    { id: 'f07', region: 'fens', name: 'The excluded middle', keystone: true,
      prose: 'Either P or not P. There is no third possibility, and proving it takes a contradiction.',
      statement: 'P | ~P',
      tools: [],
      lemma: 'Every statement is true or false.',
      hints: ['You cannot pick a side, because you know nothing about P.',
              'Deny the whole thing, and use that denial twice.',
              'Contradict, aim the denial at the goal, pick the negative side, then repeat the trick on P itself.'],
      vignette: {
        title: 'The middle nobody could exclude',
        era: 'Amsterdam and Gottingen, 1920s',
        body: ['The statement you just proved looks like nothing at all. Either it rains tomorrow or it does not. And yet it caused the loudest argument in the history of mathematics.',
               'L. E. J. Brouwer refused it. His objection was not mystical: he thought a proof should build the thing it claims exists, and the excluded middle lets you prove that something exists without ever producing it. Assume there is none, derive a contradiction, and declare victory over an object you cannot point to. David Hilbert answered that taking the excluded middle from a mathematician was like taking the telescope from an astronomer or the fists from a boxer.',
               'Hilbert won the institutional fight and Brouwer won a long argument nobody knew was still running. Constructive logic, which drops this law, turns out to be exactly the logic of computer programs: a constructive proof is a program, and a program has to produce something. Your phone runs on the losing side of that quarrel.'] } },

    { id: 'f08', region: 'fens', name: 'Contraposition',
      prose: 'If P implies Q, then denying Q denies P.',
      statement: '(P -> Q) -> (~Q -> ~P)',
      tools: [],
      lemma: 'An implication and its contrapositive stand or fall together.',
      hints: ['Three promises. The last one is a "not", which is an arrow into the impossible.',
              'Once everything is taken you hold P, an arrow from P, and a denial of its target.',
              'Suppose three times, then aim the denial at the goal.'] },

    { id: 'f09', region: 'fens', name: 'De Morgan, the first law',
      prose: 'If neither P nor Q, then not P and not Q.',
      statement: '~(P | Q) -> ~P & ~Q',
      tools: [],
      lemma: 'Denying a disjunction denies both sides.',
      hints: ['Split the goal into two denials and treat them separately.',
              'In each branch you have the denial of the whole "or" and one of its sides.',
              'Suppose, split, then in each branch suppose again and rebuild the "or".'] },

    { id: 'f10', region: 'fens', name: 'Distribution',
      prose: 'If P holds and either Q or R holds, then either both P and Q, or both P and R.',
      statement: 'P & (Q | R) -> (P & Q) | (P & R)',
      tools: [],
      lemma: 'Conjunction distributes over disjunction.',
      hints: ['The assumed "and" hands you the "or" separately.',
              'Take the two cases. In each you know which side of the goal to aim at.',
              'Suppose, cases, pick the side, split.'] },

    { id: 'f11', region: 'fens', name: 'Peirce’s law',
      prose: 'If assuming that P implies Q is enough to give you P, then P holds outright. It is true only in classical logic.',
      statement: '((P -> Q) -> P) -> P',
      tools: [],
      lemma: 'Peirce’s law.',
      hints: ['There is nothing to build P from, so deny it.',
              'Once P is denied you can prove that P implies anything.',
              'Suppose, contradict, aim the denial at the goal, then feed the big arrow what it wants.'] },

    { id: 'f12', region: 'fens', name: 'Splitting a shared conclusion',
      prose: 'If P implies Q and P implies R, then P implies both.',
      statement: '(P -> Q) & (P -> R) -> (P -> Q & R)',
      tools: [],
      lemma: 'Two implications from one hypothesis combine.',
      hints: ['Take everything you are given first, then split what you must prove.',
              'Each half of the goal has its own arrow waiting among the hypotheses.',
              'Suppose twice, split, then use one arrow on each branch.'] },

    { id: 'f13', region: 'fens', name: 'All humans are mortal',
      prose: 'The oldest argument in the West, checked by machine.',
      statement: '(all X. human(X) -> mortal(X)) -> human(Socrates) -> mortal(Socrates)',
      tools: [],
      lemma: 'A universal rule applies to any particular thing.',
      hints: ['A claim about everything is a tool you can aim at one thing.',
              'Take both promises, then point the universal rule at Socrates.',
              'Suppose twice, then use the universal hypothesis.'] },

    { id: 'f14', region: 'fens', name: 'Something, therefore not nothing',
      prose: 'If some number is even, it is not the case that every number fails to be even.',
      statement: '(ex X. even(X)) -> ~(all X. ~even(X))',
      tools: [],
      lemma: 'An existence claim refutes the matching universal denial.',
      hints: ['Both quantifiers need handling: one gives you a thing, the other consumes one.',
              'Name the number that exists, then aim the universal denial at that name.',
              'Suppose twice, name the witness, then use the universal hypothesis on it.'] }
  ];

  /* pars.js is generated by tools/par.js from the kernel's own solver */
  let P = (typeof PARS !== 'undefined') ? PARS : null;
  if (!P && typeof require !== 'undefined') { try { P = require('./pars.js'); } catch (e) { P = null; } }
  if (P) THEOREMS.forEach(t => { if (P[t.id]) t.par = P[t.id]; });

  const toolById = {};
  TOOLS.forEach(t => { toolById[t.id] = t; });
  const thmById = {};
  THEOREMS.forEach(t => { thmById[t.id] = t; });

  const api = { TOOLS: TOOLS, THEOREMS: THEOREMS, REGIONS: REGIONS, tool: id => toolById[id], theorem: id => thmById[id] };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  return api;
})();
